### ISSUE TITLE
FAIL: t/cycle while installing/Testing from source

### ISSUE THREAD

**Issue by beshoo1** [gearman/gearmand#83] opened 2017-03-08 13:38 UTC
cat ./test-suite.log
   gearmand 1.1.15: ./test-suite.log

TOTAL: 37
 PASS:  29
 SKIP:  5
 XFAIL: 2
 FAIL:  1
 XPASS: 0
 ERROR: 0

.. contents:: :depth: 2

XFAIL: bin/gearman
==================

/output/gearmand-1.1.15/bin/.libs/lt-gearman    Error in usage(No Functions were provided).

Client mode: /output/gearmand-1.1.15/bin/.libs/lt-gearman [options] [<data>]
Worker mode: /output/gearmand-1.1.15/bin/.libs/lt-gearman -w [options] [<command> [<args> ...]]

Common options to both client and worker modes.
        -f <function> - Function name to use for jobs (can give many)
        -h <host>     - Job server host
        -H            - Print this help menu
        -v            - Print diagnostic information to stdout(false)
        -p <port>     - Job server port
        -t <timeout>  - Timeout in milliseconds
        -i <pidfile>  - Create a pidfile for the process
        -S            - Enable SSL connections

Client options:
        -b            - Run jobs in the background(false)
        -I            - Run jobs as high priority
        -L            - Run jobs as low priority
        -n            - Run one job per line(false)
        -N            - Same as -n, but strip off the newline(false)
        -P            - Prefix all output lines with functions names
        -s            - Send job without reading from standard input
        -u <unique>   - Unique key to use for job

Worker options:
        -c <count>    - Number of jobs for worker to run before exiting
        -n            - Send data packet for each line(false)
        -N            - Same as -n, but strip off the newline(false)
        -w            - Run in worker mode(false)
XFAIL bin/gearman (exit status: 1)

XFAIL: bin/gearadmin
====================

No option execution operation given.

Options:
  --help                         Options related to the program.
  -h [ --host ] arg (=localhost) Connect to the host
  -p [ --port ] arg (=4730)      Port number or service to use for connection
  --server-version               Fetch the version number for the server.
  --server-verbose               Fetch the verbose setting for the server.
  --create-function arg          Create the function from the server.
  --cancel-job arg               Remove a given job from the server's queue
  --drop-function arg            Drop the function from the server.
  --show-unique-jobs             Show unique jobs on server.
  --show-jobs                    Show all jobs on the server.
  --getpid                       Get Process ID for the server.
  --status                       Status for the server.
  --priority-status              Queued jobs status by priority.
  --workers                      Workers for the server.
  -S [ --ssl ]                   Enable SSL connections.

XFAIL bin/gearadmin (exit status: 1)

SKIP: t/skip
============

SKIP t/skip (exit status: 77)

FAIL: t/cycle
=============

cycle.kill.kill                                 2:000063710 [ ok ]
cycle.worker.single startup/shutdown                                    0:000987129 [ ok ]
cycle.server_startup().server_startup(1)                                        1:002134872 [ ok ]
cycle.server_startup().server_startup(many)                                     20:041761913 [ ok ]
cycle.server_startup().shutdown_and_remove()                                    0:000148102 [ ok ]
libtest/client.cc:268: in start() pid(35239) localhost:40596 ping(libtest/client.cc:268: Connection refused), additionally pid: 37613 is alive: true waited: 17 server started. exec: /output/gearmand-1.1.15/libtool --mode=execute /output/gearmand-1.1.15/./gearmand/gearmand --verbose=INFO --log-file=var/log/gearmand.logg752a6 --pid-file=var/run/gearmand.pidBlwkNc --port=40596 -u root --listen=localhost  stderr:

tests/cycle.cc:113: in server_startup_multiple_TEST() pid(35239) Assertion '__server_startup_TEST((cycle_context_st*)obj, 20)' != 'TEST_SUCCESS'
cycle.server_startup().server_startup(many)                                     [ failed ]
cycle.server_startup().server_startup() with bind() conflict                                    0:000001026 [ ok ]
FAIL t/cycle (exit status: 1)

SKIP: t/drizzle
===============

SKIP t/drizzle (exit status: 77)

SKIP: t/memcached
=================

SKIP t/memcached (exit status: 77)

SKIP: t/postgres
================

SKIP t/postgres (exit status: 77)

SKIP: t/redis
=============

SKIP t/redis (exit status: 77)

**Comment by beshoo1** [comment] 2017-03-08 14:05
PS: i so this error in my log file

  ERROR 2017-03-08 13:55:50.000000 [  main ] Timeout occurred when calling bind() for 0.0.0.0:4730 -> libgearman-server/gearmand.cc:688

**Comment by p-alik** [comment] 2017-03-13 15:35
@beshoo1, thank you for reporting.

The only one fail in your `test-suite.log` points to well known `t/cycle` issue. See

- #50 
- #51 

Regarding your last message. It looks like in your system the port number 4730 is already occupied. Maybe an other instance of `gearmand` is running.

**Comment by beshoo1** [comment] 2017-03-13 18:26
Will it works fine for me even with that error, so who care 😇😇😇👌

**Comment by SpamapS** [comment] 2017-03-13 18:38
Yep this is a duplicate of issue #50  -- Thanks so much for reporting. Hopefully some day we can figure out how to fix and close it.

**Closed by SpamapS** 2017-03-13 18:38 UTC
