### ISSUE TITLE
Bootstrap '-d' not working

### ISSUE THREAD

**Issue by Sebiee** [gearman/gearmand#146] opened 2017-11-06 19:04 UTC
Calling "./bootstrap.sh -c -d && make" does not work.

It seems that the "-d" flag passes to the configure script the flag "--enable-debug" which removes the flag "-std=c++0x" from the compiler. This generates error at make.

A workaround for this is to force the cpp compiler command to be "g++ -std=c++0x".

> ./bootstrap.sh -c -d -o "CXX='g++ -std=c++0x'" && make

Still, it would be nice to have this solved.

**Comment by SpamapS** [comment] 2017-12-02 16:27
Sounds legit. I don't have time to debug. But, patches accepted!

**Comment by p-alik** [comment] 2018-11-06 11:14
@Sebiee, the issue is resolved in #186.
`./bootstrap.sh -c -d && make` doesn't fail anymore. (At least on my Ubuntu 16.04 with g++5)

**Closed by p-alik** 2018-11-06 11:14 UTC
Labels: bug, help wanted
