### ISSUE TITLE
Client connected to multiple servers doesn't gracefully handle a server being unavailable

### ISSUE THREAD

**Issue by nickpeirson** [gearman/gearmand#62] opened 2016-12-07 15:21 UTC
If a gearman client is connected to multiple servers and one of the servers 'goes away', the client doesn't gracefully move on to the next server. Instead the next attempt or two _(the example below shows two attempts, but I have seen it reconnect after one)_ to queue a job result in an error before the client connects to another server.

```php
$client = new GearmanClient();
$client->addServer('127.0.0.1','4730');
$client->addServer('127.0.0.1','4731');
$client->doBackground('test-func','data'); //Job added to gearmand on 4731
// gearmand on 4731 stopped
$client->doBackground('test-func','data'); //Job not added
PHP Warning:  GearmanClient::doBackground(): recv_socket(GEARMAN_LOST_CONNECTION) lost connection to server (EOF) -> libgearman/connection.cc:1181: pid(15120) in php shell code on line 1
$client->doBackground('test-func','data'); //Job not added
PHP Warning:  GearmanClient::doBackground(): _client_run_tasks(GEARMAN_LOST_CONNECTION) detected lost connection in _client_run_tasks() -> libgearman/client.cc:1495: pid(15120) in php shell code on line 1
$client->doBackground('test-func','data'); //Job added to gearmand on 4730
```

This was produced using gearmand 1.1.14, libgearman 1.1.14 and [PHP gearman extension version 2.0.2](https://github.com/wcgallego/pecl-gearman).

**Comment by esabol** [comment] 2016-12-07 16:25
Wouldn't this be an issue for the PHP gearman extension? Or are you saying the issue is with libgearman?

**Comment by nickpeirson** [comment] 2016-12-07 16:32
It looks like the PHP extension is surfacing errors from libgearman, but I don't know if the errors that are bubbling up are expected and should be handled in the PHP extension or if they can be gracefully handled in libgearman.

If they can be handled in libgearman then it means a simpler job for all clients that consume the libgearman API as there'll be less error handling to write, but it might make sense for libgearman to expose the errors and give the consumer control over how they're handled.

As neither the author of the extension or the library I don't know what the best course of action is, but I definitely think it needs addressing somewhere as it's currently possible to lose jobs when there's an active server connected to the client that I think the client should be able to fall back to.

**Comment by esabol** [comment] 2016-12-07 16:55
Cool. Is there a similar issue for the PHP gearman extension where this has been discussed? If so, let's cross-reference the issues.

**Comment by nickpeirson** [comment] 2016-12-07 17:56
The PHP extension is a bit up in the air I think. The official repository, maintained by @hjr3, is pretty dormant with the last official release being on 2013-08-29. @wcgallego has forked it to make it build against the latest version of PHP (7.x), and [this thread](https://github.com/hjr3/pecl-gearman/issues/12) makes it sound like he may take over maintenance, but no official update on that yet. 

Hopefully one of them can weigh in.

**Comment by wcgallego** [comment] 2016-12-07 17:57
Hey All,

That's correct. I've been maintaining the PHP extension for Gearman. Trying to find the right home for it, as living under one of our personal github accounts is of course leading to confusion like this

**Comment by SpamapS** [comment] 2016-12-07 19:03
I believe libgearman is doing its job fine. You should be checking ```$client->returnCode()``` after every operation. It will close that connection socket the first time because it will likely not detect the failure until a read, rather than write, just due to socket timings. When it fails mid-submission, it has to return the failure as it does, so you can react accordingly (you might not want to submit a duplicate job in case that went through somehow). If you change your test code to print out the return code, I think you'll see that you get SUCCESS in the second and third doBackground()'s. The second warning is just telling you "hey there's a connection that isn't working".

I'm closing this for now, but please do check those return codes. If I'm wrong, and the second one didn't get a SUCCESS, then this issue deserves looking into.

**Closed by SpamapS** 2016-12-07 19:03 UTC

**Comment by ziyaindia** [comment] 2020-05-22 08:45
`<?php

/**
 * @version: 5.1
 */

class FNSGearman {
    public $gmclient;
    public $taskCount = 0;

    public static $results = array();
    public static function reset(){
        GearmanResults::$results = array();
    }

    public static function completeCallback($task) {
        $unique = $task->unique();
        if ($unique != null) {
            FNSGearman::$results[$unique] = $task->data();
        }else {
            array_push(FNSGearman::$results, $task->data());
        }
    }

    public function addTask($func_name, $arguments, $context = null, $uid = null) {
        $this->taskCount++;
        $this->gmclient->addTask($func_name, $arguments, $context, $uid);
        if ($this->taskCount == MAX_GEARMAN_TASKS) {
            $this->gmclient->runTasks();
            $this->taskCount = 0;
        }
    }

    public function runTasks() {
        if ($this->taskCount > 0) 
        {
            if (! $this->gmclient->runTasks())
            {
                echo "ERROR " . $this->gmclient->error() . "\n";
                exit;
            }
        }
    }

    public function __construct() {
        $this->gmclient= new GearmanClient();
        /* add the default server */
        $this->gmclient->addServer('localhost',4730);
        $this->gmclient->setCompleteCallback("FNSGearman::completeCallback");
    }
}

?>
`

**Comment by ziyaindia** [comment] 2020-05-22 08:45
Following is my gearman client file code

`<?php

/**
 * @version: 5.1
 */

class FNSGearman {
    public $gmclient;
    public $taskCount = 0;

    public static $results = array();
    public static function reset(){
        GearmanResults::$results = array();
    }

    public static function completeCallback($task) {
        $unique = $task->unique();
        if ($unique != null) {
            FNSGearman::$results[$unique] = $task->data();
        }else {
            array_push(FNSGearman::$results, $task->data());
        }
    }

    public function addTask($func_name, $arguments, $context = null, $uid = null) {
        $this->taskCount++;
        $this->gmclient->addTask($func_name, $arguments, $context, $uid);
        if ($this->taskCount == MAX_GEARMAN_TASKS) {
            $this->gmclient->runTasks();
            $this->taskCount = 0;
        }
    }

    public function runTasks() {
        if ($this->taskCount > 0) 
        {
            if (! $this->gmclient->runTasks())
            {
                echo "ERROR " . $this->gmclient->error() . "\n";
                exit;
            }
        }
    }

    public function __construct() {
        $this->gmclient= new GearmanClient();
        /* add the default server */
        $this->gmclient->addServer('localhost',4730);
        $this->gmclient->setCompleteCallback("FNSGearman::completeCallback");
    }
}

?>
`
